<?php
 /**
 * @file
 * This module is designed to provide access to the services provided by the Google Places API.
 * Implements hook_help().
 */

use Drupal\Core\Routing\RouteMatchInterface;

function gplaces_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.gplaces':
            return t('
        <h2>Google Places API implementation for Drupal</h2>
        <h3>Instructions</h3>
        <p>Unpack in the <em>modules</em> folder (currently in the root of your Drupal 8 installation) and enable in <strong>/admin/modules</strong>.</p>
        <p>Then, visit <strong>/admin/config/development/gplaces</strong> and enter your own Google Places API key.</p>
        <h3>Attention</h3>
        <p>Most bugs have been ironed out, holes covered, features added. But this module is a work in progress. Please report bugs and suggestions, ok?</p>
      ');
    }
}
