gplaces.settings:
  type: config_object
  label: 'GPlaces settings'
  mapping:
    gplaces:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'GPlaces Search page title:'
        google_places_api_key:
          type: text
          label: 'Google Places API key:'
block.settings.gplaces_block:
  type: block_settings
  label: 'Gplaces block'
  mapping:
    gplaces_block_settings:
